import type { WorkOrderStatus } from "@/types/workOrders";

export const WORK_ORDER_STATUSES: WorkOrderStatus[] = [
  "ingested",
  "parsing_in_progress",
  "admin_attention",
  "parsed_ready",
  "categorized",
  "awaiting_client_confirmation",
  "ready_for_dispatch",
  "scheduled_in_sheet",
  "assigned",
  "accepted",
  "en_route",
  "on_site",
  "field_in_progress",
  "field_submitted_complete",
  "field_submitted_incomplete",
  "dispatcher_review",
  "follow_up_required",
  "closed",
  "cancelled",
  "duplicate_flagged",
  "ignored",
];

// Default dispatch-board row colours (hex). Aligned with the previous Tailwind tints.
export const DEFAULT_STATUS_COLORS: Record<WorkOrderStatus, string> = {
  ingested: "#e2e8f0",
  parsing_in_progress: "#fde68a",
  admin_attention: "#fecaca",
  parsed_ready: "#bae6fd",
  categorized: "#bae6fd",
  awaiting_client_confirmation: "#ffffff",
  ready_for_dispatch: "#fde047",
  scheduled_in_sheet: "#fdba74",
  assigned: "#fdba74",
  accepted: "#fdba74",
  en_route: "#fb923c",
  on_site: "#fb923c",
  field_in_progress: "#fb923c",
  field_submitted_complete: "#f87171",
  field_submitted_incomplete: "#f87171",
  dispatcher_review: "#f87171",
  follow_up_required: "#fcd34d",
  closed: "#cbd5e1",
  cancelled: "#cbd5e1",
  duplicate_flagged: "#fecaca",
  ignored: "#e2e8f0",
};

export const STATUS_COLOR_PRESETS: { label: string; hex: string }[] = [
  { label: "White", hex: "#ffffff" },
  { label: "Light grey", hex: "#e2e8f0" },
  { label: "Slate", hex: "#cbd5e1" },
  { label: "Yellow", hex: "#fde047" },
  { label: "Amber", hex: "#fcd34d" },
  { label: "Orange (light)", hex: "#fdba74" },
  { label: "Orange", hex: "#fb923c" },
  { label: "Red (light)", hex: "#fecaca" },
  { label: "Red", hex: "#f87171" },
  { label: "Crimson", hex: "#dc2626" },
  { label: "Green (light)", hex: "#bbf7d0" },
  { label: "Green", hex: "#4ade80" },
  { label: "Cyan", hex: "#67e8f9" },
  { label: "Sky", hex: "#bae6fd" },
  { label: "Blue", hex: "#60a5fa" },
  { label: "Indigo", hex: "#a5b4fc" },
  { label: "Purple", hex: "#c4b5fd" },
  { label: "Pink", hex: "#f9a8d4" },
];