/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EngineerRouteImport } from './routes/engineer'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as EngineerJobsRouteImport } from './routes/engineer.jobs'
import { Route as EngineerDiaryRouteImport } from './routes/engineer.diary'
import { Route as ContactsIdRouteImport } from './routes/contacts.$id'
import { Route as AdminReviewRouteImport } from './routes/admin.review'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminOpsRouteImport } from './routes/admin.ops'
import { Route as AdminMapRouteImport } from './routes/admin.map'
import { Route as AdminIntakeRouteImport } from './routes/admin.intake'
import { Route as AdminEngineersRouteImport } from './routes/admin.engineers'
import { Route as AdminDispatchRouteImport } from './routes/admin.dispatch'
import { Route as AdminDiaryRouteImport } from './routes/admin.diary'
import { Route as AdminCommunicationsRouteImport } from './routes/admin.communications'
import { Route as AdminBillingRouteImport } from './routes/admin.billing'
import { Route as AdminAttentionRouteImport } from './routes/admin.attention'
import { Route as EngineerJobsIdRouteImport } from './routes/engineer.jobs.$id'
import { Route as AdminReportsSystemRouteImport } from './routes/admin.reports.system'
import { Route as AdminReportsOperationsRouteImport } from './routes/admin.reports.operations'
import { Route as AdminReportsIntakeRouteImport } from './routes/admin.reports.intake'
import { Route as AdminReportsEngineersRouteImport } from './routes/admin.reports.engineers'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineerRoute = EngineerRouteImport.update({
  id: '/engineer',
  path: '/engineer',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const EngineerJobsRoute = EngineerJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => EngineerRoute,
} as any)
const EngineerDiaryRoute = EngineerDiaryRouteImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => EngineerRoute,
} as any)
const ContactsIdRoute = ContactsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ContactsRoute,
} as any)
const AdminReviewRoute = AdminReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOpsRoute = AdminOpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMapRoute = AdminMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntakeRoute = AdminIntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEngineersRoute = AdminEngineersRouteImport.update({
  id: '/engineers',
  path: '/engineers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDispatchRoute = AdminDispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiaryRoute = AdminDiaryRouteImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommunicationsRoute = AdminCommunicationsRouteImport.update({
  id: '/communications',
  path: '/communications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAttentionRoute = AdminAttentionRouteImport.update({
  id: '/attention',
  path: '/attention',
  getParentRoute: () => AdminRoute,
} as any)
const EngineerJobsIdRoute = EngineerJobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EngineerJobsRoute,
} as any)
const AdminReportsSystemRoute = AdminReportsSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AdminReportsRoute,
} as any)
const AdminReportsOperationsRoute = AdminReportsOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AdminReportsRoute,
} as any)
const AdminReportsIntakeRoute = AdminReportsIntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => AdminReportsRoute,
} as any)
const AdminReportsEngineersRoute = AdminReportsEngineersRouteImport.update({
  id: '/engineers',
  path: '/engineers',
  getParentRoute: () => AdminReportsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contacts': typeof ContactsRouteWithChildren
  '/engineer': typeof EngineerRouteWithChildren
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/attention': typeof AdminAttentionRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/communications': typeof AdminCommunicationsRoute
  '/admin/diary': typeof AdminDiaryRoute
  '/admin/dispatch': typeof AdminDispatchRoute
  '/admin/engineers': typeof AdminEngineersRoute
  '/admin/intake': typeof AdminIntakeRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/ops': typeof AdminOpsRoute
  '/admin/reports': typeof AdminReportsRouteWithChildren
  '/admin/review': typeof AdminReviewRoute
  '/contacts/$id': typeof ContactsIdRoute
  '/engineer/diary': typeof EngineerDiaryRoute
  '/engineer/jobs': typeof EngineerJobsRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/reports/engineers': typeof AdminReportsEngineersRoute
  '/admin/reports/intake': typeof AdminReportsIntakeRoute
  '/admin/reports/operations': typeof AdminReportsOperationsRoute
  '/admin/reports/system': typeof AdminReportsSystemRoute
  '/engineer/jobs/$id': typeof EngineerJobsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacts': typeof ContactsRouteWithChildren
  '/engineer': typeof EngineerRouteWithChildren
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/attention': typeof AdminAttentionRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/communications': typeof AdminCommunicationsRoute
  '/admin/diary': typeof AdminDiaryRoute
  '/admin/dispatch': typeof AdminDispatchRoute
  '/admin/engineers': typeof AdminEngineersRoute
  '/admin/intake': typeof AdminIntakeRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/ops': typeof AdminOpsRoute
  '/admin/reports': typeof AdminReportsRouteWithChildren
  '/admin/review': typeof AdminReviewRoute
  '/contacts/$id': typeof ContactsIdRoute
  '/engineer/diary': typeof EngineerDiaryRoute
  '/engineer/jobs': typeof EngineerJobsRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/admin/reports/engineers': typeof AdminReportsEngineersRoute
  '/admin/reports/intake': typeof AdminReportsIntakeRoute
  '/admin/reports/operations': typeof AdminReportsOperationsRoute
  '/admin/reports/system': typeof AdminReportsSystemRoute
  '/engineer/jobs/$id': typeof EngineerJobsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contacts': typeof ContactsRouteWithChildren
  '/engineer': typeof EngineerRouteWithChildren
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/attention': typeof AdminAttentionRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/communications': typeof AdminCommunicationsRoute
  '/admin/diary': typeof AdminDiaryRoute
  '/admin/dispatch': typeof AdminDispatchRoute
  '/admin/engineers': typeof AdminEngineersRoute
  '/admin/intake': typeof AdminIntakeRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/ops': typeof AdminOpsRoute
  '/admin/reports': typeof AdminReportsRouteWithChildren
  '/admin/review': typeof AdminReviewRoute
  '/contacts/$id': typeof ContactsIdRoute
  '/engineer/diary': typeof EngineerDiaryRoute
  '/engineer/jobs': typeof EngineerJobsRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/reports/engineers': typeof AdminReportsEngineersRoute
  '/admin/reports/intake': typeof AdminReportsIntakeRoute
  '/admin/reports/operations': typeof AdminReportsOperationsRoute
  '/admin/reports/system': typeof AdminReportsSystemRoute
  '/engineer/jobs/$id': typeof EngineerJobsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contacts'
    | '/engineer'
    | '/login'
    | '/messages'
    | '/unauthorized'
    | '/admin/attention'
    | '/admin/billing'
    | '/admin/communications'
    | '/admin/diary'
    | '/admin/dispatch'
    | '/admin/engineers'
    | '/admin/intake'
    | '/admin/map'
    | '/admin/ops'
    | '/admin/reports'
    | '/admin/review'
    | '/contacts/$id'
    | '/engineer/diary'
    | '/engineer/jobs'
    | '/admin/'
    | '/admin/reports/engineers'
    | '/admin/reports/intake'
    | '/admin/reports/operations'
    | '/admin/reports/system'
    | '/engineer/jobs/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacts'
    | '/engineer'
    | '/login'
    | '/messages'
    | '/unauthorized'
    | '/admin/attention'
    | '/admin/billing'
    | '/admin/communications'
    | '/admin/diary'
    | '/admin/dispatch'
    | '/admin/engineers'
    | '/admin/intake'
    | '/admin/map'
    | '/admin/ops'
    | '/admin/reports'
    | '/admin/review'
    | '/contacts/$id'
    | '/engineer/diary'
    | '/engineer/jobs'
    | '/admin'
    | '/admin/reports/engineers'
    | '/admin/reports/intake'
    | '/admin/reports/operations'
    | '/admin/reports/system'
    | '/engineer/jobs/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contacts'
    | '/engineer'
    | '/login'
    | '/messages'
    | '/unauthorized'
    | '/admin/attention'
    | '/admin/billing'
    | '/admin/communications'
    | '/admin/diary'
    | '/admin/dispatch'
    | '/admin/engineers'
    | '/admin/intake'
    | '/admin/map'
    | '/admin/ops'
    | '/admin/reports'
    | '/admin/review'
    | '/contacts/$id'
    | '/engineer/diary'
    | '/engineer/jobs'
    | '/admin/'
    | '/admin/reports/engineers'
    | '/admin/reports/intake'
    | '/admin/reports/operations'
    | '/admin/reports/system'
    | '/engineer/jobs/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactsRoute: typeof ContactsRouteWithChildren
  EngineerRoute: typeof EngineerRouteWithChildren
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineer': {
      id: '/engineer'
      path: '/engineer'
      fullPath: '/engineer'
      preLoaderRoute: typeof EngineerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/engineer/jobs': {
      id: '/engineer/jobs'
      path: '/jobs'
      fullPath: '/engineer/jobs'
      preLoaderRoute: typeof EngineerJobsRouteImport
      parentRoute: typeof EngineerRoute
    }
    '/engineer/diary': {
      id: '/engineer/diary'
      path: '/diary'
      fullPath: '/engineer/diary'
      preLoaderRoute: typeof EngineerDiaryRouteImport
      parentRoute: typeof EngineerRoute
    }
    '/contacts/$id': {
      id: '/contacts/$id'
      path: '/$id'
      fullPath: '/contacts/$id'
      preLoaderRoute: typeof ContactsIdRouteImport
      parentRoute: typeof ContactsRoute
    }
    '/admin/review': {
      id: '/admin/review'
      path: '/review'
      fullPath: '/admin/review'
      preLoaderRoute: typeof AdminReviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ops': {
      id: '/admin/ops'
      path: '/ops'
      fullPath: '/admin/ops'
      preLoaderRoute: typeof AdminOpsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/map': {
      id: '/admin/map'
      path: '/map'
      fullPath: '/admin/map'
      preLoaderRoute: typeof AdminMapRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/intake': {
      id: '/admin/intake'
      path: '/intake'
      fullPath: '/admin/intake'
      preLoaderRoute: typeof AdminIntakeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/engineers': {
      id: '/admin/engineers'
      path: '/engineers'
      fullPath: '/admin/engineers'
      preLoaderRoute: typeof AdminEngineersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dispatch': {
      id: '/admin/dispatch'
      path: '/dispatch'
      fullPath: '/admin/dispatch'
      preLoaderRoute: typeof AdminDispatchRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/diary': {
      id: '/admin/diary'
      path: '/diary'
      fullPath: '/admin/diary'
      preLoaderRoute: typeof AdminDiaryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/communications': {
      id: '/admin/communications'
      path: '/communications'
      fullPath: '/admin/communications'
      preLoaderRoute: typeof AdminCommunicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attention': {
      id: '/admin/attention'
      path: '/attention'
      fullPath: '/admin/attention'
      preLoaderRoute: typeof AdminAttentionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/engineer/jobs/$id': {
      id: '/engineer/jobs/$id'
      path: '/$id'
      fullPath: '/engineer/jobs/$id'
      preLoaderRoute: typeof EngineerJobsIdRouteImport
      parentRoute: typeof EngineerJobsRoute
    }
    '/admin/reports/system': {
      id: '/admin/reports/system'
      path: '/system'
      fullPath: '/admin/reports/system'
      preLoaderRoute: typeof AdminReportsSystemRouteImport
      parentRoute: typeof AdminReportsRoute
    }
    '/admin/reports/operations': {
      id: '/admin/reports/operations'
      path: '/operations'
      fullPath: '/admin/reports/operations'
      preLoaderRoute: typeof AdminReportsOperationsRouteImport
      parentRoute: typeof AdminReportsRoute
    }
    '/admin/reports/intake': {
      id: '/admin/reports/intake'
      path: '/intake'
      fullPath: '/admin/reports/intake'
      preLoaderRoute: typeof AdminReportsIntakeRouteImport
      parentRoute: typeof AdminReportsRoute
    }
    '/admin/reports/engineers': {
      id: '/admin/reports/engineers'
      path: '/engineers'
      fullPath: '/admin/reports/engineers'
      preLoaderRoute: typeof AdminReportsEngineersRouteImport
      parentRoute: typeof AdminReportsRoute
    }
  }
}

interface AdminReportsRouteChildren {
  AdminReportsEngineersRoute: typeof AdminReportsEngineersRoute
  AdminReportsIntakeRoute: typeof AdminReportsIntakeRoute
  AdminReportsOperationsRoute: typeof AdminReportsOperationsRoute
  AdminReportsSystemRoute: typeof AdminReportsSystemRoute
}

const AdminReportsRouteChildren: AdminReportsRouteChildren = {
  AdminReportsEngineersRoute: AdminReportsEngineersRoute,
  AdminReportsIntakeRoute: AdminReportsIntakeRoute,
  AdminReportsOperationsRoute: AdminReportsOperationsRoute,
  AdminReportsSystemRoute: AdminReportsSystemRoute,
}

const AdminReportsRouteWithChildren = AdminReportsRoute._addFileChildren(
  AdminReportsRouteChildren,
)

interface AdminRouteChildren {
  AdminAttentionRoute: typeof AdminAttentionRoute
  AdminBillingRoute: typeof AdminBillingRoute
  AdminCommunicationsRoute: typeof AdminCommunicationsRoute
  AdminDiaryRoute: typeof AdminDiaryRoute
  AdminDispatchRoute: typeof AdminDispatchRoute
  AdminEngineersRoute: typeof AdminEngineersRoute
  AdminIntakeRoute: typeof AdminIntakeRoute
  AdminMapRoute: typeof AdminMapRoute
  AdminOpsRoute: typeof AdminOpsRoute
  AdminReportsRoute: typeof AdminReportsRouteWithChildren
  AdminReviewRoute: typeof AdminReviewRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAttentionRoute: AdminAttentionRoute,
  AdminBillingRoute: AdminBillingRoute,
  AdminCommunicationsRoute: AdminCommunicationsRoute,
  AdminDiaryRoute: AdminDiaryRoute,
  AdminDispatchRoute: AdminDispatchRoute,
  AdminEngineersRoute: AdminEngineersRoute,
  AdminIntakeRoute: AdminIntakeRoute,
  AdminMapRoute: AdminMapRoute,
  AdminOpsRoute: AdminOpsRoute,
  AdminReportsRoute: AdminReportsRouteWithChildren,
  AdminReviewRoute: AdminReviewRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ContactsRouteChildren {
  ContactsIdRoute: typeof ContactsIdRoute
}

const ContactsRouteChildren: ContactsRouteChildren = {
  ContactsIdRoute: ContactsIdRoute,
}

const ContactsRouteWithChildren = ContactsRoute._addFileChildren(
  ContactsRouteChildren,
)

interface EngineerJobsRouteChildren {
  EngineerJobsIdRoute: typeof EngineerJobsIdRoute
}

const EngineerJobsRouteChildren: EngineerJobsRouteChildren = {
  EngineerJobsIdRoute: EngineerJobsIdRoute,
}

const EngineerJobsRouteWithChildren = EngineerJobsRoute._addFileChildren(
  EngineerJobsRouteChildren,
)

interface EngineerRouteChildren {
  EngineerDiaryRoute: typeof EngineerDiaryRoute
  EngineerJobsRoute: typeof EngineerJobsRouteWithChildren
}

const EngineerRouteChildren: EngineerRouteChildren = {
  EngineerDiaryRoute: EngineerDiaryRoute,
  EngineerJobsRoute: EngineerJobsRouteWithChildren,
}

const EngineerRouteWithChildren = EngineerRoute._addFileChildren(
  EngineerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactsRoute: ContactsRouteWithChildren,
  EngineerRoute: EngineerRouteWithChildren,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
